name: CI

on:
  push:
    branchs: [secrets]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print node version 
        env:
          NODE_ENV_TEST: ${{ secrets.NODE_ENV_TEST }}
        run: |
          echo "Node version: $NODE_ENV_TEST"

      - name: Show Github variables
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"